version: '3'

services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=postgres

  solargraph:
    build:
      context: './docker-solargraph'
      dockerfile: 'Dockerfile'
    volumes:
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - '8091:7658'

  web:
    build:
      context: './docker-rails'
      dockerfile: 'Dockerfile'
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails_app:/myapp
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - solargraph
volumes:
  bundle_path:
